window.SITE_COPY = {
  "zh-cn": {
    "brand": "佳裕云智",
    "nav.idea": "我们怎么想",
    "nav.services": "服务",
    "nav.work": "成果",
    "nav.contact": "联系",
    "nav.cta": "联系我们",
    "hero.sub": "帮助企业把 AI 贯穿在业务里。",
    "hero.cta1": "联系我们",
    "ap.title": "诊断、落地、陪跑，同一批人。",
    "inc.kicker": "我们怎么想",
    "inc.title": "把 AI 装进业务，长出新的增长。",
    "inc.lead": "以前太贵、太慢、腾不出人做不了的事，现在第一次做得起。",
    "work.kicker": "我们在做的",
    "work.title": "目前在做的几个项目。",
    "svc.title": "从系统到 AI 到运维，一站做齐。",
    "svc.lead": "业务系统、可控 AI、AI 搜索可见度、平台接管，你不用在几家供应商之间来回对接。",
    "svc.1.t": "业务系统与工作台搭建",
    "svc.1.d": "按你实际的流程搭后台系统和团队工作台，把散在表格和人工里的环节固定下来。",
    "svc.2.t": "可控 AI 接入",
    "svc.2.d": "把 AI 接进你现有的系统，讲清它能做什么、边界在哪、出错怎么退回，人始终可复核。",
    "svc.2.a1": "网关",
    "svc.2.a2": "护栏",
    "svc.2.a3": "影子模式",
    "svc.2.a4": "人工出口",
    "svc.3.t": "AI 搜索可见度（GEO）",
    "svc.3.d": "让品牌和内容更容易被 ChatGPT、豆包、DeepSeek 检索和引用。先做可见度诊断，再按范围优化——不承诺必然被引用。",
    "svc.4.t": "系统接管与持续运维",
    "svc.4.d": "接手已有平台，先做结构与风险评估，再负责日常运维和按需的二次开发。",
    "ap.1.t": "先把事情看清楚",
    "ap.1.d": "先做一次 AI 可行性诊断：把流程走一遍、把数据盘一盘，再按“值不值得做、风险多大、数据够不够”给每个场景打分，最后给你一份看得懂的路线图。",
    "ap.2.t": "一件一件做",
    "ap.2.d": "选中的场景先在影子模式里跑通、跟人工比对，确认真的靠谱再放开来用。一项一报价，见效了再往下做。",
    "ap.3.t": "长期陪着",
    "ap.3.d": "上线不是终点。日常运维、每月一起复盘、需要时再做二次开发，系统一直有人在管着。",
    "bd.title": "AI 负责整理，人负责决定。",
    "bd.lead": "涉及会员、患者和付款这些高风险的事，我们先想的是边界怎么定，而不是 AI 能做多少。",
    "bd.2t": "先立规矩，再接 AI",
    "bd.2d": "数据怎么分级、谁能看、存哪里、留多久，接进 AI 之前先定清楚。",
    "bd.4t": "系统只打下手",
    "bd.4d": "收件、分类、把缺口标出来，剩下的判断交给人。",
    "ct.title": "联系我们",
    "ct.lead": "把你手上最想做、却一直没做成的那件事告诉我们，我们先一起把它看清楚。",
    "ct.btn": "发邮件给我们",
    "ct.note": "如果这个页面是别人分享给你的，也可以直接联系分享给你的人。",
    "ft.legalName": "佳裕云智（深圳）科技有限公司",
    "hero.title": "佳裕云智 · 你的 AI 增长伙伴",
    "skip": "跳到正文",
    "menu": "菜单",
    "close": "关闭",
    "hero.line1": "你的 AI",
    "hero.line2": "增长伙伴",
    "hero.offer": "企业 AI 咨询 · 系统落地 · 长期陪跑",
    "hero.art": "蓝色纸带折成相连的门，连接一叠文件与下一段工作",
    "demo.cta": "看一段工作怎样落地",
    "inc.new": "新的服务入口，更完整的客户跟进，有依据的专业协作。先从一件值得做的事开始。",
    "work.intro": "先看一份资料，怎样走完一段工作。",
    "office.category": "办公与财务流转",
    "office.title": "一份申请，从补齐资料到审批办理。",
    "office.desc": "为教育出版场景开发办公与财务流转，把申请、附件、资料补正、审批及办理记录串起来。不同岗位按权限查看资料。",
    "office.status": "已发布演示站",
    "office.scope": "业务试用及正式验收待确认",
    "office.details": "我方工作与交付范围",
    "case.contribution": "我方工作",
    "case.status": "当前状态",
    "case.boundary": "适用范围",
    "case.more": "查看过程与分工",
    "office.contribution": "申请与多附件、齐备校验、角色待办、审批退回、统一费用汇总及操作记录。",
    "office.evidence": "2026 年 9 月 14 日完成改版演示站发布与验证；正式账号及业务试用另行推进。",
    "office.boundary": "用于办公申请和财务流转，不是总账、审计意见或报税系统；专业判断由相应人员负责。",
    "demo.name": "办公流转",
    "demo.badge": "交互示例 · 虚构资料",
    "demo.reset": "重新演示",
    "demo.instruction": "点选步骤，或在右侧走一遍示例。",
    "demo.caption": "按办公流转功能制作的交互示例。全部资料虚构，不上传文件、不调用 AI、不触发实际审批或付款。",
    "stage.0": "收件",
    "stage.1": "补正",
    "stage.2": "复核",
    "stage.3": "跟进",
    "stage.0.sub": "把申请接进来",
    "stage.1.sub": "缺什么，说明白",
    "stage.2.sub": "由负责人决定",
    "stage.3.sub": "下一步，有人接",
    "doc.title": "办公用品采购申请",
    "doc.id": "示例单据 · DEMO-001",
    "doc.field.type": "申请类别",
    "doc.type": "办公用品",
    "doc.field.owner": "提交人",
    "doc.owner": "业务同事 A（虚构）",
    "doc.field.amount": "申请金额（示例）",
    "doc.field.item": "采购说明",
    "doc.item": "活动资料与办公文具",
    "doc.attachment": "采购证明",
    "doc.missing": "待补齐",
    "doc.attached": "示例附件已补齐",
    "doc.state.0": "草稿",
    "doc.state.1": "待补正",
    "doc.state.2": "待人工复核",
    "doc.state.3": "待办理",
    "doc.note.0": "先核对申请与附件。缺项会明确列出，资料不会直接进入审批。",
    "doc.note.1": "需要补充采购证明。示例只添加预设附件，不接收你的真实文件。",
    "doc.note.ready": "所需资料已补齐，可以送交负责人复核。",
    "doc.note.2": "资料齐备不等于审批通过。是否办理，由审批人核对后决定。",
    "doc.note.3": "流程来到办理岗位。记录下一步与责任人，不把“已转交”当作“已完成”。",
    "doc.role": "当前责任人",
    "doc.role.submitter": "提交人",
    "doc.role.reviewer": "审批人",
    "doc.role.handler": "办理人员",
    "doc.check": "检查资料",
    "doc.add": "补入示例附件",
    "doc.submit": "送交复核",
    "doc.approve": "确认进入办理",
    "doc.return": "退回补正",
    "doc.review.title": "原始资料可核对",
    "doc.review.desc": "申请内容与示例附件同时保留。",
    "doc.access.title": "岗位权限分开",
    "doc.access.desc": "办理人员只查看对应阶段所需资料。",
    "doc.timeline.1": "申请与附件齐备",
    "doc.timeline.1.d": "由提交人补充并送交复核",
    "doc.timeline.2": "人工复核通过（示例）",
    "doc.timeline.2.d": "审批意见与版本记录保留",
    "doc.timeline.3": "等待办理回执",
    "doc.timeline.3.d": "责任人：办理人员 · 本例未发生实际付款",
    "doc.returned": "示例已退回，请重新补齐附件。",
    "platform.category": "教育出版平台",
    "platform.title": "接住正在运行的系统，持续把它做好。",
    "platform.desc": "参与平台接管、持续维护、功能开发与接口协作，按业务路径核对、测试和交付。",
    "platform.state": "持续技术服务 · 协作开发",
    "platform.visual.top": "教育出版 · 数字平台",
    "platform.visual.title": "让知识\n继续流动。",
    "platform.visual.bottom": "接管 / 开发 / 协作 / 维护",
    "platform.detail.title": "从接管到持续交付",
    "platform.detail": "先盘点系统、账号与维护风险，再与合作团队明确接口和职责。日常运维与二次开发分别管理，逐项记录验证和交付。",
    "platform.boundary": "本案例说明我方参与的技术工作，不将合作平台全部能力或用户规模算作我方独立成果。",
    "geo.category": "医疗 GEO · AI 搜索可见度",
    "geo.title": "把 AI 搜索中的问题，变成可跟进的工作。",
    "geo.desc": "整理多引擎回答、资料来源和待处理问题，支持内容复核与复测，让新渠道有持续经营的方法。",
    "geo.state": "监测与跟进工具 · 图中为演示数据",
    "geo.detail.title": "检测 → 分派 → 复核 → 复测",
    "geo.detail": "固定问题与引擎范围，记录回答、来源和日期；整理事实纠错与内容任务，再在一致口径下复测。发布与重要判断保留人工审核。",
    "geo.boundary": "示例图中的数字不代表客户成效。实际结果应注明日期、样本和计算口径，不承诺排名或必然曝光。",
    "geo.image.caption": "GEO 控制台示例图 · 虚构演示数字，非客户成效；界面语言为简体中文。",
    "geo.image.alt": "GEO 检测控制台，包含虚构示例指标",
    "geo.zoom": "放大 GEO 演示界面",
    "medical.view": "也看看医疗工作台示例 ↗",
    "medical.caption": "医疗运营工作台 · 按业务结构重绘，全部为演示数据，不含真实客户身份；界面语言为简体中文。",
    "accounting.label": "专业服务 · 可以从这里开始",
    "accounting.title": "让专业的人，接到更完整的资料。",
    "accounting.desc": "把办公流转经验延伸到客户资料收件、补件与内部复核。先选一个小范围，用虚构样例验证工作方式。",
    "accounting.1": "客户资料收件",
    "accounting.1.d": "一份清单，知道已经收到什么。",
    "accounting.2": "缺漏与疑点整理",
    "accounting.2.d": "标出待补资料，保留原文来源。",
    "accounting.3": "专业人员复核",
    "accounting.3.d": "谁来判断、下一步做什么，都清楚。",
    "accounting.note": "可讨论的延伸方向，尚非已交付会计产品。不自动形成审计意见、税务结论或法律判断。",
    "ai.scope": "按项目配置模型入口、权限、规则检查和复核出口，接入前明确资料范围与调用路径。",
    "boundary.sources.title": "来源与缺口一起看",
    "boundary.sources.desc": "按场景保留原始资料和待核事项。找不到依据时，留下问题交人确认。",
    "contact.copy": "复制联系方式",
    "brief.download": "带走一页介绍 ↓",
    "brief.title": "佳裕云智 · 企业 AI 咨询与落地",
    "brief.note": "生成日期：2026-09-20。办公案例状态依据 2026-09-14 发布记录；不代表其他模块同日完成验收。",
    "share": "复制本案例链接",
    "copy.success": "已复制",
    "copy.manual": "请选择并复制以下内容",
    "brief.ready": "一页介绍已生成，可离线打开或打印为 PDF。"
  },
  "zh-hk": {
    "brand": "佳裕雲智",
    "nav.idea": "我們怎麼想",
    "nav.services": "服務",
    "nav.work": "成果",
    "nav.contact": "聯絡",
    "nav.cta": "聯絡我們",
    "hero.sub": "幫助企業把 AI 貫穿在業務裡。",
    "hero.cta1": "聯絡我們",
    "ap.title": "診斷、落地、陪跑，同一批人。",
    "inc.kicker": "我們怎麼想",
    "inc.title": "把 AI 裝進業務，長出新的增長。",
    "inc.lead": "以前太貴、太慢、騰不出人做不了的事，現在第一次做得起。",
    "work.kicker": "我們在做的",
    "work.title": "目前在做的幾個項目。",
    "svc.title": "從系統到 AI 到運維，一站做齊。",
    "svc.lead": "業務系統、可控 AI、AI 搜尋可見度、平台接管，你不用在幾家供應商之間來回對接。",
    "svc.1.t": "業務系統與工作台",
    "svc.1.d": "按你實際的流程做後台系統和團隊工作台，把散在試算表和人手裡的環節固定下來。",
    "svc.2.t": "可控 AI 接入",
    "svc.2.d": "把 AI 接進你現有的系統，講清它能做甚麼、邊界在哪、出錯怎麼退回，人始終可覆核。",
    "svc.2.a1": "網關",
    "svc.2.a2": "護欄",
    "svc.2.a3": "影子模式",
    "svc.2.a4": "人工出口",
    "svc.3.t": "AI 搜尋可見度（GEO）",
    "svc.3.d": "讓品牌和內容更容易被 ChatGPT、豆包、DeepSeek 檢索和引用。先做可見度診斷，再按範圍優化——不承諾必然被引用。",
    "svc.4.t": "系統接管與持續運維",
    "svc.4.d": "接手已有平台，先做結構與風險評估，再負責日常運維和按需的二次開發。",
    "ap.1.t": "先把事情看清楚",
    "ap.1.d": "先做一次 AI 可行性診斷：把流程走一遍、把數據盤一盤，再按「值不值得做、風險多大、數據夠不夠」給每個場景打分，最後給你一份看得懂的路線圖。",
    "ap.2.t": "一件一件做",
    "ap.2.d": "選中的場景先在影子模式裡跑通、跟人工比對，確認真的靠譜再放開來用。一項一報價，見效了再往下做。",
    "ap.3.t": "長期陪著",
    "ap.3.d": "上線不是終點。日常運維、每月一起複盤、需要時再做二次開發，系統一直有人在管著。",
    "bd.title": "AI 負責整理，人負責決定。",
    "bd.lead": "涉及會員、患者和付款這些高風險的事，我們先想的是邊界怎麼定，而不是 AI 能做多少。",
    "bd.2t": "先立規矩，再接 AI",
    "bd.2d": "資料怎麼分級、誰能看、存哪裡、留多久，接進 AI 之前先定清楚。",
    "bd.4t": "系統只打下手",
    "bd.4d": "收件、分類、把缺口標出來，剩下的判斷交給人。",
    "ct.title": "聯絡我們",
    "ct.lead": "把你手上最想做、卻一直沒做成的那件事告訴我們，我們先一起把它看清楚。",
    "ct.btn": "發電郵給我們",
    "ct.note": "如果這個頁面是別人分享給你的，也可以直接聯絡分享給你的人。",
    "ft.legalName": "佳裕雲智（深圳）科技有限公司",
    "hero.title": "佳裕雲智 · 你的 AI 增長夥伴",
    "skip": "跳到正文",
    "menu": "選單",
    "close": "關閉",
    "hero.line1": "你的 AI",
    "hero.line2": "增長夥伴",
    "hero.offer": "企業 AI 諮詢 · 系統落地 · 長期陪跑",
    "hero.art": "藍色紙帶摺成相連的門，連接一疊文件與下一段工作",
    "demo.cta": "看一段工作怎樣落地",
    "inc.new": "新的服務入口，更完整的客戶跟進，有依據的專業協作。先從一件值得做的事開始。",
    "work.intro": "先看一份資料，怎樣走完一段工作。",
    "office.category": "辦公與財務流轉",
    "office.title": "一份申請，從補齊資料到審批辦理。",
    "office.desc": "為教育出版場景開發辦公與財務流轉，把申請、附件、資料補正、審批及辦理記錄串起來。不同崗位按權限查看資料。",
    "office.status": "已發布演示站",
    "office.scope": "業務試用及正式驗收待確認",
    "office.details": "我方工作與交付範圍",
    "case.contribution": "我方工作",
    "case.status": "目前狀態",
    "case.boundary": "適用範圍",
    "case.more": "查看過程與分工",
    "office.contribution": "申請與多附件、齊備校驗、角色待辦、審批退回、統一費用彙總及操作記錄。",
    "office.evidence": "2026 年 9 月 14 日完成改版演示站發布與驗證；正式帳號及業務試用另行推進。",
    "office.boundary": "用於辦公申請和財務流轉，不是總帳、審計意見或報稅系統；專業判斷由相應人員負責。",
    "demo.name": "辦公流轉",
    "demo.badge": "互動示例 · 虛構資料",
    "demo.reset": "重新演示",
    "demo.instruction": "點選步驟，或在右側走一遍示例。",
    "demo.caption": "按辦公流轉功能製作的互動示例。全部資料虛構，不上傳文件、不調用 AI、不觸發實際審批或付款。",
    "stage.0": "收件",
    "stage.1": "補正",
    "stage.2": "覆核",
    "stage.3": "跟進",
    "stage.0.sub": "把申請接進來",
    "stage.1.sub": "缺甚麼，說明白",
    "stage.2.sub": "由負責人決定",
    "stage.3.sub": "下一步，有人接",
    "doc.title": "辦公用品採購申請",
    "doc.id": "示例單據 · DEMO-001",
    "doc.field.type": "申請類別",
    "doc.type": "辦公用品",
    "doc.field.owner": "提交人",
    "doc.owner": "業務同事 A（虛構）",
    "doc.field.amount": "申請金額（示例）",
    "doc.field.item": "採購說明",
    "doc.item": "活動資料與辦公文具",
    "doc.attachment": "採購證明",
    "doc.missing": "待補齊",
    "doc.attached": "示例附件已補齊",
    "doc.state.0": "草稿",
    "doc.state.1": "待補正",
    "doc.state.2": "待人工覆核",
    "doc.state.3": "待辦理",
    "doc.note.0": "先核對申請與附件。缺項會明確列出，資料不會直接進入審批。",
    "doc.note.1": "需要補充採購證明。示例只添加預設附件，不接收你的真實文件。",
    "doc.note.ready": "所需資料已補齊，可以送交負責人覆核。",
    "doc.note.2": "資料齊備不等於審批通過。是否辦理，由審批人核對後決定。",
    "doc.note.3": "流程來到辦理崗位。記錄下一步與負責人，不把「已轉交」當作「已完成」。",
    "doc.role": "目前負責人",
    "doc.role.submitter": "提交人",
    "doc.role.reviewer": "審批人",
    "doc.role.handler": "辦理人員",
    "doc.check": "檢查資料",
    "doc.add": "補入示例附件",
    "doc.submit": "送交覆核",
    "doc.approve": "確認進入辦理",
    "doc.return": "退回補正",
    "doc.review.title": "原始資料可核對",
    "doc.review.desc": "申請內容與示例附件同時保留。",
    "doc.access.title": "崗位權限分開",
    "doc.access.desc": "辦理人員只查看對應階段所需資料。",
    "doc.timeline.1": "申請與附件齊備",
    "doc.timeline.1.d": "由提交人補充並送交覆核",
    "doc.timeline.2": "人工覆核通過（示例）",
    "doc.timeline.2.d": "審批意見與版本記錄保留",
    "doc.timeline.3": "等待辦理回執",
    "doc.timeline.3.d": "負責人：辦理人員 · 本例未發生實際付款",
    "doc.returned": "示例已退回，請重新補齊附件。",
    "platform.category": "教育出版平台",
    "platform.title": "接住正在運行的系統，持續把它做好。",
    "platform.desc": "參與平台接管、持續維護、功能開發與接口協作，按業務路徑核對、測試和交付。",
    "platform.state": "持續技術服務 · 協作開發",
    "platform.visual.top": "教育出版 · 數碼平台",
    "platform.visual.title": "讓知識\n繼續流動。",
    "platform.visual.bottom": "接管 / 開發 / 協作 / 維護",
    "platform.detail.title": "從接管到持續交付",
    "platform.detail": "先盤點系統、帳號與維護風險，再與合作團隊明確接口和職責。日常運維與二次開發分別管理，逐項記錄驗證和交付。",
    "platform.boundary": "本案例說明我方參與的技術工作，不將合作平台全部能力或用戶規模算作我方獨立成果。",
    "geo.category": "醫療 GEO · AI 搜尋可見度",
    "geo.title": "把 AI 搜尋中的問題，變成可跟進的工作。",
    "geo.desc": "整理多引擎回答、資料來源和待處理問題，支援內容覆核與複測，讓新渠道有持續經營的方法。",
    "geo.state": "監測與跟進工具 · 圖中為演示數據",
    "geo.detail.title": "檢測 → 分派 → 覆核 → 複測",
    "geo.detail": "固定問題與引擎範圍，記錄回答、來源和日期；整理事實糾錯與內容任務，再在一致口徑下複測。發布與重要判斷保留人工審核。",
    "geo.boundary": "示例圖中的數字不代表客戶成效。實際結果應註明日期、樣本和計算口徑，不承諾排名或必然曝光。",
    "geo.image.caption": "GEO 控制台示例圖 · 虛構演示數字，非客戶成效；介面語言為簡體中文。",
    "geo.image.alt": "GEO 檢測控制台，包含虛構示例指標",
    "geo.zoom": "放大 GEO 演示介面",
    "medical.view": "也看看醫療工作台示例 ↗",
    "medical.caption": "醫療營運工作台 · 按業務結構重繪，全部為演示數據，不含真實客戶身份；介面語言為簡體中文。",
    "accounting.label": "專業服務 · 可以從這裡開始",
    "accounting.title": "讓專業的人，接到更完整的資料。",
    "accounting.desc": "把辦公流轉經驗延伸到客戶資料收件、補件與內部覆核。先選一個小範圍，用虛構樣例驗證工作方式。",
    "accounting.1": "客戶資料收件",
    "accounting.1.d": "一份清單，知道已經收到甚麼。",
    "accounting.2": "缺漏與疑點整理",
    "accounting.2.d": "標出待補資料，保留原文來源。",
    "accounting.3": "專業人員覆核",
    "accounting.3.d": "誰來判斷、下一步做甚麼，都清楚。",
    "accounting.note": "可討論的延伸方向，尚非已交付會計產品。不自動形成審計意見、稅務結論或法律判斷。",
    "ai.scope": "按項目配置模型入口、權限、規則檢查和覆核出口，接入前明確資料範圍與調用路徑。",
    "boundary.sources.title": "來源與缺口一起看",
    "boundary.sources.desc": "按場景保留原始資料和待核事項。找不到依據時，留下問題交人確認。",
    "contact.copy": "複製聯絡方式",
    "brief.download": "帶走一頁介紹 ↓",
    "brief.title": "佳裕雲智 · 企業 AI 諮詢與落地",
    "brief.note": "生成日期：2026-09-20。辦公案例狀態依據 2026-09-14 發布記錄；不代表其他模組同日完成驗收。",
    "share": "複製本案例連結",
    "copy.success": "已複製",
    "copy.manual": "請選取並複製以下內容",
    "brief.ready": "一頁介紹已生成，可離線開啟或列印為 PDF。"
  },
  "en": {
    "brand": "Junemoon",
    "nav.idea": "How we think",
    "nav.services": "Services",
    "nav.work": "Work",
    "nav.contact": "Contact",
    "nav.cta": "Contact us",
    "hero.sub": "We help companies weave AI through their business.",
    "hero.cta1": "Talk to us",
    "ap.title": "Diagnosis, delivery, support — the same people.",
    "inc.kicker": "How we think",
    "inc.title": "Put AI into your business, and grow something new.",
    "inc.lead": "The things that were too expensive, too slow, or too short-staffed before — doable for the first time.",
    "work.kicker": "What we're on",
    "work.title": "A few projects we're working on now.",
    "svc.title": "From systems to AI to ops — done in one place.",
    "svc.lead": "Business systems, controllable AI, AI-search visibility, platform takeover — no juggling several vendors.",
    "svc.1.t": "Business Systems & Workbench",
    "svc.1.d": "We build the back-office systems and team workbenches that fit how your business already runs.",
    "svc.2.t": "Controllable AI Integration",
    "svc.2.d": "We add AI into the systems you already use — with clear boundaries, safe fallbacks, and human review kept in place.",
    "svc.2.a1": "Gateway",
    "svc.2.a2": "Guardrails",
    "svc.2.a3": "Shadow mode",
    "svc.2.a4": "Human exit",
    "svc.3.t": "AI Search Visibility (GEO)",
    "svc.3.d": "We make your brand easier for ChatGPT, Doubao and DeepSeek to find, parse and cite — starting with a diagnostic, not a guarantee.",
    "svc.4.t": "Takeover & Operations",
    "svc.4.d": "We take over an existing platform, assess its structure and risks first, then run and extend it as you need.",
    "ap.1.t": "Sell the judgement first",
    "ap.1.d": "We start with an AI-readiness diagnostic: process walk-through, data inventory, and scenarios scored on value × risk × data-readiness — you get a roadmap you can actually read.",
    "ap.2.t": "Deliver item by item",
    "ap.2.d": "The chosen scenario runs in shadow mode with human comparison first; we open it up only once it proves out. Priced per item, continued when it works.",
    "ap.3.t": "Year-round support",
    "ap.3.d": "Launch isn't the finish line. Daily operations, monthly reviews, and secondary development on demand — the system always has someone tending it.",
    "bd.title": "AI does the sorting. People make the call.",
    "bd.lead": "For high-risk matters — members, patients, payments — we think first about where the line sits, not about how much the AI can do.",
    "bd.2t": "Rules first, then AI",
    "bd.2d": "Classification, access, storage, retention — all settled before any AI is connected.",
    "bd.4t": "The system only assists",
    "bd.4d": "It takes in, sorts, and flags the gaps — the judgement is left to people.",
    "ct.title": "Talk to us about one specific thing.",
    "ct.lead": "Tell us the thing you most want to do but never managed to — we'll get clear on it with you first.",
    "ct.btn": "Email us",
    "ct.note": "If someone shared this page with you, you can also just reach out to them directly.",
    "ft.legalName": "佳裕云智（深圳）科技有限公司",
    "hero.title": "Junemoon · Your AI growth partner",
    "skip": "Skip to content",
    "menu": "Menu",
    "close": "Close",
    "hero.line1": "Your AI",
    "hero.line2": "growth partner",
    "hero.offer": "AI consulting · Engineering · Ongoing support",
    "hero.art": "A blue paper ribbon forms connected gateways, carrying documents into the next stage of work",
    "demo.cta": "Explore a working example",
    "inc.new": "A new service channel. Better client follow-through. Evidence for professional review. Start with one worthwhile opportunity.",
    "work.intro": "Follow one request from its first document to the next action.",
    "office.category": "Office & finance workflows",
    "office.title": "One request. Complete information. A clear next step.",
    "office.desc": "Developed for an education publishing context: requests, attachments, corrections, approvals and handling records in one workflow. Each role sees the information its permissions allow.",
    "office.status": "Demo site released",
    "office.scope": "Business trial and formal acceptance pending confirmation",
    "office.details": "Our contribution and delivery scope",
    "case.contribution": "Our contribution",
    "case.status": "Current status",
    "case.boundary": "Scope",
    "case.more": "Explore the process and responsibilities",
    "office.contribution": "Requests and multiple attachments, completeness checks, role-based tasks, returns for correction, expense summaries and activity records.",
    "office.evidence": "The updated demo was released and verified on 14 September 2026. Production account setup and the business trial are separate next steps.",
    "office.boundary": "Designed for office requests and finance workflows, not a general ledger, audit opinion or tax filing system. Professional decisions remain with the responsible people.",
    "demo.name": "Office workflow",
    "demo.badge": "Interactive sample · Fictional data",
    "demo.reset": "Reset",
    "demo.instruction": "Select a step or work through the sample on the right.",
    "demo.caption": "An interactive illustration of office workflow features. All data is fictional. No files are uploaded, no AI is called and no real approval or payment is made.",
    "stage.0": "Receive",
    "stage.1": "Complete",
    "stage.2": "Review",
    "stage.3": "Follow up",
    "stage.0.sub": "Capture the request",
    "stage.1.sub": "Identify what is missing",
    "stage.2.sub": "A person makes the decision",
    "stage.3.sub": "Assign the next action",
    "doc.title": "Office supplies request",
    "doc.id": "Sample request · DEMO-001",
    "doc.field.type": "Request type",
    "doc.type": "Office supplies",
    "doc.field.owner": "Submitted by",
    "doc.owner": "Colleague A (fictional)",
    "doc.field.amount": "Requested amount (sample)",
    "doc.field.item": "Description",
    "doc.item": "Event materials and stationery",
    "doc.attachment": "Purchase evidence",
    "doc.missing": "Missing",
    "doc.attached": "Sample attachment added",
    "doc.state.0": "Draft",
    "doc.state.1": "Needs information",
    "doc.state.2": "Awaiting review",
    "doc.state.3": "Ready for handling",
    "doc.note.0": "Check the request and its attachments first. Missing items are listed before the request can enter approval.",
    "doc.note.1": "Purchase evidence is required. This sample adds a preset attachment; it does not accept your files.",
    "doc.note.ready": "The required information is complete and ready for the reviewer.",
    "doc.note.2": "Complete information is not approval. The reviewer checks the request and decides whether it should proceed.",
    "doc.note.3": "The next role receives a clear action. A handoff is recorded separately from completion.",
    "doc.role": "Responsible role",
    "doc.role.submitter": "Submitter",
    "doc.role.reviewer": "Reviewer",
    "doc.role.handler": "Handler",
    "doc.check": "Check information",
    "doc.add": "Add sample attachment",
    "doc.submit": "Send for review",
    "doc.approve": "Confirm handoff",
    "doc.return": "Return",
    "doc.review.title": "Source available",
    "doc.review.desc": "The request and its sample attachment stay together.",
    "doc.access.title": "Separate role permissions",
    "doc.access.desc": "The handler sees information needed for the relevant stage.",
    "doc.timeline.1": "Request and attachment complete",
    "doc.timeline.1.d": "Completed and submitted by the requester",
    "doc.timeline.2": "Human review completed (sample)",
    "doc.timeline.2.d": "Decision and revision history retained",
    "doc.timeline.3": "Awaiting handling receipt",
    "doc.timeline.3.d": "Assigned to the handler. No actual payment has taken place.",
    "doc.returned": "Sample returned. Please add the attachment again.",
    "platform.category": "Education publishing platform",
    "platform.title": "Take over a running platform. Keep improving it.",
    "platform.desc": "We participate in platform takeover, maintenance, feature development and integration, verifying and delivering against real workflows.",
    "platform.state": "Ongoing technical service · Collaborative development",
    "platform.visual.top": "Education · Digital publishing",
    "platform.visual.title": "Keep knowledge\nmoving.",
    "platform.visual.bottom": "Take over / Develop / Collaborate / Maintain",
    "platform.detail.title": "From takeover to ongoing delivery",
    "platform.detail": "We inventory systems, accounts and maintenance risks, then agree responsibilities and interfaces with the partner team. Operations and feature work are tracked separately, with verification and delivery recorded for each item.",
    "platform.boundary": "This case describes our technical contribution, not ownership of every platform feature or the platform’s overall user base.",
    "geo.category": "Healthcare GEO · AI search visibility",
    "geo.title": "Turn AI search findings into work someone can follow through.",
    "geo.desc": "Organise answers, sources and issues across AI engines. Support content review and repeat measurements, giving this new channel a repeatable operating process.",
    "geo.state": "Monitoring and follow-up tools · Sample data shown",
    "geo.detail.title": "Measure → Assign → Review → Recheck",
    "geo.detail": "Use a consistent set of questions and engines, with answers, sources and dates recorded. Assign factual corrections and content tasks, then recheck on the same basis. Publication and significant decisions retain human review.",
    "geo.boundary": "Numbers in the illustration are not client results. Actual measurements require dates, samples and definitions. Rankings and exposure are not guaranteed.",
    "geo.image.caption": "GEO console illustration. Fictional figures, not client results. The illustrated interface is in Simplified Chinese.",
    "geo.image.alt": "GEO console illustration with fictional sample metrics",
    "geo.zoom": "Enlarge the GEO illustration",
    "medical.view": "View the medical workbench example ↗",
    "medical.caption": "Medical operations workbench, redrawn around the workflow. All data is fictional; no real client identities. Interface shown in Simplified Chinese.",
    "accounting.label": "Professional services · A starting point",
    "accounting.title": "Give professionals a more complete picture.",
    "accounting.desc": "Apply our workflow experience to client document intake, missing information and internal review. Start with a small scope and validate it using fictional examples.",
    "accounting.1": "Client document intake",
    "accounting.1.d": "One checklist showing what has arrived.",
    "accounting.2": "Gaps and questions",
    "accounting.2.d": "Flag missing information and retain its source.",
    "accounting.3": "Professional review",
    "accounting.3.d": "A clear decision owner and next action.",
    "accounting.note": "A direction to explore, not an accounting product already delivered. It does not automatically produce audit opinions, tax conclusions or legal judgements.",
    "ai.scope": "Configure model access, permissions, rule checks and human review for the project. Define data scope and model-call paths before connecting them.",
    "boundary.sources.title": "Show sources and gaps together",
    "boundary.sources.desc": "Retain source material and questions requiring verification. When evidence is missing, flag the question for a person.",
    "contact.copy": "Copy contact details",
    "brief.download": "Download a one-page brief ↓",
    "brief.title": "Junemoon · Enterprise AI consulting and delivery",
    "brief.note": "Prepared 20 September 2026. Office case status is based on the 14 September release record; this does not imply acceptance of all other modules.",
    "share": "Copy case link",
    "copy.success": "Copied",
    "copy.manual": "Select and copy the text below",
    "brief.ready": "Brief downloaded. Open offline or print it as a PDF."
  }
};
