/* New case evidence and delivery descriptions; original positioning stays in content.js. */
(() => {
 const rows={
  'hero.cta':['看我们做过的','看我們做過的','See our work'],
  'work.lead':['从已有项目里，看具体做法和交付。','從已有項目裏，看具體做法和交付。','See the work, the deliverables, and how they were checked.'],
  'work.jump.edu':['教育平台与 AI 录入','教育平台與 AI 錄入','Education & AI-assisted entry'],
  'work.jump.scan':['扫描归档与期限跟进','掃描歸檔與期限跟進','Document filing & follow-up'],
  'work.jump.geo':['医疗 AI 搜索监测','醫療 AI 搜尋監測','Healthcare AI visibility'],
  'edu.status':['2026 年 7 月 · 功能上线及真实试卷验收记录','2026 年 7 月 · 功能上線及真實試卷驗收紀錄','July 2026 · release and real-paper acceptance records'],
  'edu.title':['让已有内容，进入新的业务流程。','讓已有內容，進入新的業務流程。','Put existing content to work in new ways.'],
  'edu.desc':['在教育出版平台的持续开发中，把 PDF 和图片试卷转成可编辑的题目草稿，再由编辑核对、查重、确认入库。','在教育出版平台的持續開發中，把 PDF 和圖片試卷轉成可編輯的題目草稿，再由編輯核對、查重、確認入庫。','For an education publishing platform, we built a flow from PDF and image-based exam papers to editable question drafts, duplicate checks and editor-confirmed import.'],
  'edu.flow.1':['上传材料','上傳材料','Source files'], 'edu.flow.2':['识别草稿','識別草稿','Draft extraction'], 'edu.flow.3':['人工核对','人工核對','Editor review'], 'edu.flow.4':['确认入库','確認入庫','Confirmed import'],
  'edu.row.1.t':['交付的功能','交付的功能','What we delivered'],
  'edu.row.1.d':['材料上传、题目预览与修改、重复题提示、分类检索；已记录支持 6 类题型。','材料上傳、題目預覽與修改、重複題提示、分類檢索；已記錄支援 6 類題型。','Upload, preview and editing, duplicate warnings, and category search. The release record covers six question types.'],
  'edu.row.2.t':['用真实材料复验','用真實材料複驗','Checked against real material'],
  'edu.row.2.d':['验收发现阅读原文遗漏后，修复题组结构；同一份材料复测，原文与 5 道关联小题完整保留。','驗收發現閱讀原文遺漏後，修復題組結構；同一份材料複測，原文與 5 道關聯小題完整保留。','An acceptance test exposed a missing reading passage. We fixed the grouping and retested the same paper, preserving the passage and its five related questions.'],
  'edu.row.3.t':['系统能持续迭代','系統能持續迭代','A maintainable release path'],
  'edu.row.3.d':['同一平台的接管工作包含资产盘点、独立发布链、版本对应与回退资料，支持后续维护和开发。','同一平台的接管工作包括資產盤點、獨立發布鏈、版本對應與回退資料，支援後續維護和開發。','Our takeover work on the same platform included an asset inventory, an independent release pipeline, version records and rollback information.'],
  'edu.scope':['以上为我方参与的工作与历史验收范围；新增题型、扩大使用范围另行验证。','以上為我方參與的工作與歷史驗收範圍；新增題型、擴大使用範圍另行驗證。','These are our contributions and the historical acceptance scope. Further question types and wider use need separate validation.'],
  'scan.category':['文档处理 · 专业服务场景','文件處理 · 專業服務場景','Document workflows · professional services'],
  'scan.title':['从扫描原件，到能跟进的清单。','從掃描原件，到能跟進的清單。','From a scanned document to a usable follow-up list.'],
  'scan.desc':['识别公司、文件类别和明示日期。经办人对照原件确认后，建立归档副本，另存期限清单；保留原期限、延期历史和人工备注。','識別公司、文件類別和明示日期。經辦人對照原件確認後，建立歸檔副本，另存期限清單；保留原期限、延期歷史和人手備註。','Extract the company, document type and explicit dates. After a person checks the original, create a filed copy and export a deadline list, preserving original dates, extensions and notes.'],
  'scan.status':['2026 年 9 月 · Windows 本地试用版，使用自制文件验证','2026 年 9 月 · Windows 本機試用版，使用自製文件驗證','September 2026 · Windows local trial, tested with synthetic documents'],
  'scan.input':['输入样例：扫描通知','輸入樣例：掃描通知','Input example: scanned notice'],
  'scan.output':['输出样例：实际导出的 Excel 清单','輸出樣例：實際匯出的 Excel 清單','Output example: an actual exported Excel list'],
  'scan.caption':['项目中的自制测试资料及实际导出结果，均为虚构公司与事项；图片为繁体中文。不是客户真实档案，也不代表客户文件识别率。','項目中的自製測試資料及實際匯出結果，均為虛構公司與事項；圖片為繁體中文。並非客戶真實檔案，亦不代表客戶文件識別率。','Synthetic test documents and actual exported output from the project, using fictional companies and items. Images are in Traditional Chinese. They do not establish accuracy on client documents.'],
  'scan.zoom':['放大查看','放大查看','View full size'],
  'scan.open':['打开原图 ↗','開啟原圖 ↗','Open original image ↗'],
  'scan.point.1.t':['原件留底','原件留底','Keep the original'],
  'scan.point.1.d':['先预览目录与文件名，确认后另建归档副本。','先預覽目錄與檔案名稱，確認後另建歸檔副本。','Preview the folder and filename before creating a filed copy.'],
  'scan.point.2.t':['不确定就待核','不確定就待核','Keep uncertainty visible'],
  'scan.point.2.d':['有歧义的公司或日期保留原文，不直接写进正式清单。','有歧義的公司或日期保留原文，不直接寫進正式清單。','Ambiguous companies or dates retain their source text and stay out of the confirmed list.'],
  'scan.point.3.t':['交付能继续使用','交付能繼續使用','Make the output usable'],
  'scan.point.3.d':['输出文件与八栏 Excel，保留负责人、状态、备注和来源文件名。','輸出檔案與八欄 Excel，保留負責人、狀態、備註和來源檔案名稱。','Deliver filed documents and an eight-column Excel list with owners, status, notes and source filenames.'],
  'scan.scope':['试用包已验证；真实客户文件的准确率、处理用时和现有清单对接，留到试点中确认。','試用包已驗證；真實客戶文件的準確率、處理時間及現有清單接駁，留待試點確認。','The trial package has been tested. Accuracy on client files, handling time and integration with existing lists need a pilot.'],
  'geo.status':['已有多引擎检测、报告及 CSV 明细导出','已有多引擎檢測、報告及 CSV 明細匯出','Multi-engine checks, reports and CSV exports implemented'],
  'geo.focus':['不只看有没有提到，还看说得对不对。','不只看有沒有提到，還看說得對不對。','Measure whether the brand appears, and whether the answer is right.'],
  'geo.desc':['按品牌词、泛需求、费用及到院信息等问题分组，检查模型回答、引用依据和竞品同屏，再形成内容纠错与复测清单。','按品牌詞、一般需求、費用及到院資訊等問題分組，檢查模型回答、引用依據和競品同屏，再形成內容糾錯與複測清單。','Group questions by brand, general needs, fees and visit information. Review model answers, evidence and competing mentions, then create correction and retest tasks.'],
  'geo.engines':['检测接入','檢測接入','Engine integrations'],
  'geo.dimensions':['报告维度','報告維度','Report dimensions'],
  'geo.dimensions.d':['可见性 · 推荐强度 · 事实准确性 · 证据质量 · 专科匹配度','可見性 · 推薦強度 · 事實準確性 · 證據品質 · 專科匹配度','Visibility · recommendation strength · factual accuracy · evidence quality · specialty relevance'],
  'geo.exports':['交付明细','交付明細','Exported evidence'],
  'geo.exports.d':['问题分类、模型与原始回答、是否提及、竞品、扣分问题及综合说明。','問題分類、模型與原始回答、是否提及、競品、扣分問題及綜合說明。','Question category, model and original answer, mentions, competitors, scoring issues and assessment notes.'],
  'geo.measure':['复测方式','複測方式','Retest method'],
  'geo.measure.d':['固定问题组和引擎范围，记录检测日期；在一致口径下比较结果。','固定問題組和引擎範圍，記錄檢測日期；在一致口徑下比較結果。','Keep questions and engine scope consistent, record test dates, and compare like for like.'],
  'geo.scope':['已有检测不等于保证排名或引用。不同批次不能直接相减作为效果；提升幅度需有同口径前后记录。','已有檢測不等於保證排名或引用。不同批次不能直接相減作為成效；提升幅度須有同一口徑的前後紀錄。','Monitoring does not guarantee ranking or citation. Improvement claims need comparable before-and-after records.'],
  'office.short':['申请与附件、缺件补正、角色待办、审批退回、费用汇总及操作记录，串成一段可追踪的流程。','申請與附件、缺件補正、角色待辦、審批退回、費用彙總及操作紀錄，串成一段可追蹤的流程。','Applications, attachments, missing-information requests, role-based tasks, returns, expense summaries and activity records form one traceable workflow.'],
  'delivery.title':['合作之后，具体拿到什么。','合作之後，具體拿到甚麼。','What you get from working with us.'],
  'delivery.lead':['交付内容按项目范围约定，能看懂、能验收，也能交接给下一位同事。','交付內容按項目範圍約定，能看懂、能驗收，也能交接給下一位同事。','Deliverables are agreed to scope: understandable, verifiable, and ready to hand over.'],
  'delivery.1.t':['业务判断','業務判斷','Business direction'],
  'delivery.1.d':['场景清单、优先级、资料与权限边界、分期路线图。','場景清單、優先次序、資料與權限邊界、分期路線圖。','Use cases, priorities, data and access boundaries, and a phased roadmap.'],
  'delivery.2.t':['可用的成果','可用的成果','Working outputs'],
  'delivery.2.d':['业务原型、系统功能、可使用的文件或报表，以及使用说明。','業務原型、系統功能、可使用的檔案或報表，以及使用說明。','A workflow prototype, software features, usable files or reports, and instructions.'],
  'delivery.3.t':['验证与交接','驗證與交接','Verification & handover'],
  'delivery.3.d':['样本结果、修改记录、已知限制；涉及开发时提供约定源码、部署与恢复资料。','樣本結果、修改紀錄、已知限制；涉及開發時提供約定源碼、部署與恢復資料。','Sample results, changes and known limits; agreed source code, deployment and recovery information for development work.'],
  'delivery.4.t':['持续改进','持續改進','Ongoing improvement'],
  'delivery.4.d':['问题清单、后续负责人、复盘记录与下一阶段的改进范围。','問題清單、後續負責人、覆盤紀錄與下一階段的改進範圍。','Open issues, owners, review notes and the scope of the next improvement.'],
  'method.title':['AI 接入，要把这些事做实。','AI 接入，要把這些事做實。','Make AI integration accountable.'],
  'method.lead':['作为项目设计和验收要点，按实际场景落实。','作為項目設計和驗收要點，按實際場景落實。','Design and acceptance criteria, applied to the scope of each project.'],
  'method.1.t':['资料与调用范围','資料與調用範圍','Data & model access'],
  'method.1.d':['确认哪些资料可以传给模型、在哪里处理与保存；模型入口统一管理，按需设置调用额度和记录。','確認哪些資料可以傳給模型、在哪裏處理與保存；模型入口統一管理，按需設定調用額度和紀錄。','Agree what data may reach a model and where it is processed and stored. Manage model access centrally, with appropriate usage limits and records.'],
  'method.2.t':['权限由系统执行','權限由系統執行','Enforce permissions in the system'],
  'method.2.d':['只开放任务所需的资料和工具；读取、修改、发送分开授权，不能让模型自己判断有没有权限。','只開放任務所需的資料和工具；讀取、修改、發送分開授權，不能讓模型自行判斷有沒有權限。','Expose only the data and tools the task needs. Authorize reading, editing and sending separately in the application.'],
  'method.3.t':['输出能回头核对','輸出能回頭核對','Keep outputs traceable'],
  'method.3.d':['保留原件、引用或页码；不确定的字段进入待核清单，关键写入和对外动作经人确认。','保留原件、引用或頁碼；不確定的欄位進入待核清單，關鍵寫入及對外動作經人確認。','Retain originals, citations or page references. Route uncertain fields for review and require human confirmation for consequential actions.'],
  'method.4.t':['上线前有比较，上线后有退路','上線前有比較，上線後有退路','Evaluate before launch; keep a recovery path'],
  'method.4.d':['用同一批代表样本和失败样例比对，记录质量、修改量及完整处理用时；保留版本、回退和后续复测安排。','用同一批代表樣本和失敗樣例比對，記錄品質、修改量及完整處理時間；保留版本、回退及後續複測安排。','Compare representative and failure samples. Record quality, corrections and end-to-end time, with versioning, rollback and retesting.'],
  'method.refs':['设计参考：','設計參考：','Design references: '],
  'method.note':['公开方法参考，不表示获得认证或背书。','公開方法參考，不表示獲得認證或背書。','Public guidance, not a certification or endorsement.'],
  'brief.note':['内容更新：2026-10-01。案例状态按各自记录说明；样例验证不等于客户业务验收。','內容更新：2026-10-01。案例狀態按各自紀錄說明；樣例驗證不等於客戶業務驗收。','Updated 1 October 2026. Case status follows the respective records; sample validation is not client acceptance.']
 };
 ['zh-cn','zh-hk','en'].forEach((lang,i)=>Object.entries(rows).forEach(([key,value])=>window.SITE_COPY[lang]['e.'+key]=value[i]));
})();
