/* Additive copy only: the approved company copy remains in content.js. */
(() => {
  const copy = {
    'path.0':['诊断','診斷','Discover'], 'path.1':['落地','落地','Build'], 'path.2':['陪跑','陪跑','Evolve'],
    'path.out.0':['一份看得懂的路线图','一份看得懂的路線圖','A roadmap you can act on'],
    'path.out.1':['一个可以亲手试用的场景','一個可以親手試用的場景','A working scenario to try'],
    'path.out.2':['一个持续生长的系统','一個持續生長的系統','A system that keeps evolving'],
    'path.caption':['点一下，看看每一步留下什么。','點一下，看看每一步留下甚麼。','Choose a step. See what it leaves you with.'],
    'path.output':['交付','交付','DELIVERABLE'],
    'case.office':['办公流转','辦公流轉','Office workflows'],
    'case.platform':['教育平台','教育平台','Education platform'],
    'case.geo':['AI 搜索可见度','AI 搜尋可見度','AI visibility'],
    'case.choose':['选择一个项目','選擇一個項目','Choose a project'],
    'case.explore':['试一试增长实验','試一試增長實驗','Try a growth experiment'],
    'platform.sample':['交付过程示意 · 非客户记录','交付過程示意 · 非客戶紀錄','Illustrative workflow · not a client record'],
    'platform.0':['盘点系统','盤點系統','Map the system'],
    'platform.1':['明确协作','明確協作','Align the work'],
    'platform.2':['持续交付','持續交付','Keep shipping'],
    'platform.title.0':['先知道，接住了什么。','先知道，接住了甚麼。','Know what you are taking on.'],
    'platform.title.1':['把接口和分工，讲清楚。','把接口和分工，講清楚。','Make interfaces and ownership clear.'],
    'platform.title.2':['每一次更新，都有来处。','每一次更新，都有來處。','Make every update traceable.'],
    'platform.label.0':['系统清单','系統清單','System inventory'],
    'platform.label.1':['协作清单','協作清單','Collaboration checklist'],
    'platform.label.2':['交付清单','交付清單','Delivery checklist'],
    'platform.row.0a':['应用与账号','應用與帳號','Applications & accounts'],
    'platform.row.0b':['接口与依赖','接口與依賴','Interfaces & dependencies'],
    'platform.row.0c':['维护风险','維護風險','Maintenance risks'],
    'platform.row.1a':['需求与范围','需求與範圍','Requirements & scope'],
    'platform.row.1b':['接口约定','接口約定','Interface contracts'],
    'platform.row.1c':['责任与验收方式','責任與驗收方式','Ownership & acceptance'],
    'platform.row.2a':['变更说明','變更說明','Change notes'],
    'platform.row.2b':['验证记录','驗證紀錄','Verification records'],
    'platform.row.2c':['交接与后续事项','交接與後續事項','Handover & next actions'],
    'platform.note':['点选步骤，查看这一阶段需要留下的资料。','點選步驟，查看這一階段需要留下的資料。','Choose a stage to explore the records it needs.'],
    'geo.sample':['虚构问题 · 流程示例','虛構問題 · 流程示例','Fictional question · workflow example'],
    'geo.question':['示例机构的服务时间是什么？','示例機構的服務時間是甚麼？','What are the example clinic’s opening hours?'],
    'geo.answer':['AI 回答','AI 回答','AI answer'],
    'geo.answer.text':['“周末也开放。”','「週末也開放。」','“Open on weekends, too.”'],
    'geo.source':['可核对的资料','可核對的資料','Source to check'],
    'geo.source.text':['机构资料只说明周一至周五开放，周末未注明。','機構資料只說明星期一至五開放，週末未註明。','The clinic’s information lists weekdays only. Weekends are not specified.'],
    'geo.issue':['发现资料缺口','發現資料缺口','Information gap found'],
    'geo.review':['待内容负责人核对','待內容負責人核對','Awaiting the content owner’s review'],
    'geo.retest':['复测安排已记录','復測安排已記錄','Retest plan recorded'],
    'geo.action.0':['加入复核清单','加入覆核清單','Add to review list'],
    'geo.action.1':['记录复测安排','記錄復測安排','Plan a retest'],
    'geo.action.2':['重新体验','重新體驗','Start again'],
    'geo.note.0':['回答里的判断，没有在资料中找到依据。','回答裏的判斷，未能在資料中找到依據。','The statement is not supported by the available source.'],
    'geo.note.1':['先确认实际服务时间，再补全可公开资料。','先確認實際服務時間，再補全可公開資料。','Confirm the actual hours, then update the public information.'],
    'geo.note.2':['沿用同一问题与引擎范围，等待后续检测结果。','沿用同一問題與引擎範圍，等待後續檢測結果。','Keep the question and engine scope consistent. Results are still pending.'],
    'geo.view':['查看控制台示例图','查看控制台示例圖','View the example dashboard'],
    'lab.label':['Junemoon 实验室','Junemoon 實驗室','Junemoon Lab'],
    'lab.title':['以前没空做的事，\n从一个想法开始。','以前沒空做的事，\n從一個想法開始。','The thing you never had time for.\nStart with an idea.'],
    'lab.desc':['比如，一场商场周末活动。换一组条件，看看它可以长成什么样。','例如，一場商場週末活動。換一組條件，看看它可以長成甚麼樣。','Take a weekend event at a shopping centre. Change the brief and explore what it could become.'],
    'lab.audience':['为谁设计','為誰設計','Who is it for?'],
    'lab.family':['亲子家庭','親子家庭','Families'],
    'lab.young':['年轻客群','年輕客群','Young adults'],
    'lab.local':['周边居民','附近居民','Neighbours'],
    'lab.theme':['从什么出发','從甚麼出發','Start with a theme'],
    'lab.make':['动手创作','動手創作','Making things'],
    'lab.night':['夜间探索','夜間探索','After hours'],
    'lab.green':['绿色生活','綠色生活','Greener living'],
    'lab.run':['组合一个方案','組合一個方案','Compose a concept'],
    'lab.download':['带走这个想法 ↓','帶走這個想法 ↓','Take this idea ↓'],
    'lab.note':['概念体验 · 使用预设组合，不调用 AI；不代表已交付项目。','概念體驗 · 使用預設組合，不調用 AI；不代表已交付項目。','Concept experience · preset combinations, no AI call. Not a delivered project.'],
    'lab.plan':['从创意到行动','從創意到行動','From idea to action'],
    'lab.event':['活动','活動','Event'], 'lab.material':['物料','物料','Materials'], 'lab.follow':['跟进','跟進','Follow-up'],
    'lab.poster.make':['把周末，\n留给好奇心。','把週末，\n留給好奇心。','Make room\nfor curiosity.'],
    'lab.poster.night':['天黑以后，\n再多逛一会。','天黑以後，\n再多逛一會。','Stay a little\nafter dark.'],
    'lab.poster.green':['把一点绿色，\n带回日常。','把一點綠色，\n帶回日常。','Bring a little\ngreen home.'],
    'lab.event.make':['开放手作桌与作品展示','開放手作桌與作品展示','Open maker tables and a shared showcase'],
    'lab.event.night':['灯光寻迹与夜间打卡路线','燈光尋跡與夜間打卡路線','A light trail and an evening discovery route'],
    'lab.event.green':['旧物交换与小型种植体验','舊物交換與小型種植體驗','A swap corner and a planting workshop'],
    'lab.audience.family':['设置亲子协作环节与休息区。','設置親子協作環節與休息區。','Include shared family activities and a rest area.'],
    'lab.audience.young':['设置朋友组队环节与创作分享位。','設置朋友組隊環節與創作分享位。','Add team activities and a space to share creations.'],
    'lab.audience.local':['设置邻里交流环节与轻量报名入口。','設置鄰里交流環節與簡單報名入口。','Add a neighbourhood exchange and a simple signup.'],
    'lab.material.make':['招募海报、材料清单、桌面指引','招募海報、材料清單、桌面指引','Invitation poster, supply list, table instructions'],
    'lab.material.night':['路线图、点位标识、商户参与说明','路線圖、點位標識、商戶參與說明','Route map, location signs, retailer briefing'],
    'lab.material.green':['交换规则、种植说明、现场标识','交換規則、種植說明、現場標識','Swap rules, planting guide, event signage'],
    'lab.follow.family':['经同意收集体验反馈，邀请下一次亲子活动。','經同意收集體驗意見，邀請參加下一次親子活動。','Collect feedback with consent and invite families to the next event.'],
    'lab.follow.young':['经同意整理作品与反馈，邀请下一期共创。','經同意整理作品與意見，邀請參加下一期共創。','With consent, collect creations and feedback for the next collaboration.'],
    'lab.follow.local':['经同意收集邻里建议，安排下一次社区主题。','經同意收集鄰里建議，安排下一次社區主題。','Collect local suggestions with consent to plan the next community theme.'],
    'lab.applied':['方案已更新','方案已更新','Concept updated'],
    'lab.pending':['条件已改变，点击按钮更新方案。','條件已改變，點擊按鈕更新方案。','Brief changed. Compose to update the concept.'],
    'lab.ready':['可以换一组条件，再试一次。','可以換一組條件，再試一次。','Try a different brief to explore another direction.'],
    'lab.concept':['活动概念样例','活動概念樣例','EVENT CONCEPT'],
    'lab.download.note':['这是预设概念样例。执行前仍需确认预算、场地、人员与活动安排。','這是預設概念樣例。執行前仍需確認預算、場地、人員與活動安排。','This is a preset concept. Budget, venue, staffing and event arrangements still need confirmation.']
  };
  ['zh-cn','zh-hk','en'].forEach((lang,i) => Object.entries(copy).forEach(([key,values]) => {window.SITE_COPY[lang]['studio.'+key]=values[i];}));
})();
